### ISSUE TITLE
P3 Pro gives error 403

### ISSUE THREAD

**Issue by Behem07h** [shishu94/Klipperotchy#10]
I'm using https://github.com/shishu94/Klipperotchy/tree/main/tools/serial_moonraker_bridge
My setup: P3 Pro ->  USB A to USB C cable -> Female USB C CH340E -> Male USB A CH340G -> RPi 4

Both USB to TTL converters are set to 3.3V and the Tx and Rx lines are crossed correctly. I have verified that my USB A to USB C cable is a data cable

I am running the serial moonraker bridge macro using 230400 baud, /dev/ttyUSB0, localhost:7125. I have matching settings on the palette side. When run, it prints:
'4:26 PM Command {start_serial_moonraker_bridge} finished
4:26 PM baudrate=230400 serial=/dev/ttyUSB0 moonraker=localhost:7125
4:26 PM Running Command {start_serial_moonraker_bridge}...:
4:26 PM START_SERIAL_MOONRAKER_BRIDGE '

I then go to canvas to connect the P3, but pressing "connect" gives me 'Device error: 403'

What am I doing wrong?

**Comment by Behem07h** [comment]
i tried running it manually in putty, and i am getting this error:
`pi@mainsailos:~/Klipperotchy/tools/serial_moonraker_bridge $ python3 serial_moonraker_bridge.py --baudrate=115200 --moonraker=[localhost:7125] --serial=/dev/ttyUSB0 &
[2] 2680
[1]   Exit 2                  python3 serial_moonraker_bridge.py --baudrate=230400 --moonraker=[localhost:7125] --serial=/dev/ttyUSB0
pi@mainsailos:~/Klipperotchy/tools/serial_moonraker_bridge $ Traceback (most recent call last):
  File "/home/pi/Klipperotchy/tools/serial_moonraker_bridge/serial_moonraker_bridge.py", line 34, in <module>
    checkMoonraker()
  File "/home/pi/Klipperotchy/tools/serial_moonraker_bridge/serial_moonraker_bridge.py", line 28, in checkMoonraker
    conn.request("POST", "/printer/info")
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
python3 serial_moonraker_bridge.py --baudrate=115200 --moonraker=[mainsailos.local:7125] --serial=/dev/ttyUSB0 &
`

this happens with both localhost:7125 and mainsail.local:7125.  i have verified that this port number is correct based on my moonraker config file.

accessing the url using my web browser works fine 
![image](https://github.com/user-attachments/assets/9d1ebddb-487c-483d-b1eb-df675ad4202a)



edit:  localhost or 0.0.0.0 by itself seems to work. Looks like the readme and default config is not correct about needing to specify the port.

it also seems quite problematic to me that none of these errors are reported in the klipper console when running using the macro, despite the supposed "verbose" setting in the cfg file

**Comment by Behem07h** [comment]
After fixing the moonraker connection issue, it reports "Listening palette  Listening moonraker", but still does not connect. It doesnt throw any error

On the palette side i have autoconnect enabled and am clicking connect from the canvas web interface but am still getting error 403. on the palette lcd the connect button is greyed out.


if i spam the connect button on canvas, occasionally i get a "successfully connected to printer", but it doesnt actually connect (the Status and controls panel remains empty and the connection menu says not connected)

**Comment by shishu94** [comment]
Hi, I checked what you describe and here are a few things that you can try:
- On the ip:port you do need the port, the only thing that i see from you logs is that you kept the brackets "[...]". These are just a placeholder. Please try without the brackets.  Either localhost:7125 or mainsail.local:7125 should work. 0.0.0.0 might work but that really depends on your setup so I don't advise for it.  

- Once this is set and you actually see "Listening palette Listening moonraker", this means that the bridge is listening but not that the P3 is ready.

- Do you have any way to test that your serial to serial is working as intended ? (you could use https://linux.die.net/man/1/screen by connected both sides to the same pc/laptop and listen on 2 different terminals)

- On the P3, please disable the autoconnect. Until the setup is known to work, it only makes the debuging more complex.

- Then edit the P3 setup manually. 
- The com port, once you connect the  CH340, should show up on the P3. If it doesn't, this means that the P3 doesn't recognize the serial adapter.
- The baudrate, 115200 is known to work with most of the adapters I tried. I recommend using that for now.

Hope this help.

**Comment by Behem07h** [comment]
- Trying it using `$  python3 serial_moonraker_bridge.py --baudrate=115200 --moonraker=localhost:7125 --serial=/dev/ttyUSB0 &`, It reports "Listening palette Listening moonraker", but it still returns error 403 on the palette. Occasionally it reports "Successfully connected to printer", but it does not actually connect

- Using putty, I have verified that I can send commands between the two serial adapters., in both directions.

- I have also disabled the autoconnect on my palette for these tests

- I am setting the connection settings manually to 115200 baud

- on the P3, with the adapter unplugged I do not see any ports, and when I connect the adapter I see /dev/ttyUSB0 in the canvas connections menu as expected. 


image: "successfully connected to printer" but no printer actually connected
![image](https://github.com/user-attachments/assets/518a3da1-14db-449f-b402-74a00197d579)

**Comment by Behem07h** [comment]
Hi, do you have any idea what might be causing the issue?
Please let me know if there is any other information you might need
